# -*- coding: utf-8 -*-
"""Bigdata Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLPXoeVUKgMyJLLb36ARl6dbMN3DyT0O
"""

!pip install pyspark -q

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, year, month, when, concat_ws

spark = SparkSession.builder.appName("CrimeAnalysis").getOrCreate()

import pandas as pd
from datetime import datetime

sample_data = {
    "DATE OCC": [datetime(2023, 5, 12), datetime(2023, 6, 15), datetime(2023, 5, 18)],
    "TIME OCC": [2300, 1345, 745],
    "AREA NAME": ["Hollywood", "Wilshire", "Southwest"],
    "Crm Cd Desc": ["BURGLARY", "ROBBERY", "ASSAULT"],
    "Vict Age": [22, 35, 17],
    "Vict Sex": ["M", "F", "M"],
    "Vict Descent": ["H", "W", "B"]
}

df = pd.DataFrame(sample_data)
df.to_csv("Crime_Data_from_2020_to_Present.csv", index=False)

df = spark.read.csv("Crime_Data_from_2020_to_Present.csv", header=True, inferSchema=True)

df = df.withColumnRenamed("AREA NAME", "Area_Name") \
       .withColumnRenamed("Crm Cd Desc", "Crime_Description") \
       .withColumnRenamed("Vict Age", "Victim_Age") \
       .withColumnRenamed("Vict Sex", "Victim_Sex") \
       .withColumnRenamed("Vict Descent", "Victim_Descent") \
       .withColumn("YearMonth", concat_ws("-", year(col("DATE OCC")), month(col("DATE OCC"))))

df_monthly_crime = df.groupBy("YearMonth").count().orderBy("YearMonth")
pdf_monthly_crime = df_monthly_crime.toPandas()

plt.figure(figsize=(12, 5))
plt.plot(pdf_monthly_crime["YearMonth"], pdf_monthly_crime["count"], marker='o')
plt.xticks(rotation=45)
plt.title("Crime Trends Over Time")
plt.xlabel("Year-Month")
plt.ylabel("Crime Count")
plt.grid(True)
plt.show()

df_violent_area = df.groupBy("Area_Name").count().orderBy(col("count").desc())
pdf_violent_area = df_violent_area.toPandas()

plt.figure(figsize=(12, 5))
sns.barplot(x="Area_Name", y="count", data=pdf_violent_area.head(10))
plt.xticks(rotation=45)
plt.title("Top 10 Most Dangerous Areas")
plt.xlabel("Area Name")
plt.ylabel("Crime Count")
plt.show()

df_time = df.withColumn("Time_of_Day",
    when((col("TIME OCC") >= 0) & (col("TIME OCC") < 600), "Midnight - Morning")
    .when((col("TIME OCC") >= 600) & (col("TIME OCC") < 1200), "Morning - Noon")
    .when((col("TIME OCC") >= 1200) & (col("TIME OCC") < 1800), "Afternoon - Evening")
    .otherwise("Evening - Midnight"))

pdf_time = df_time.groupBy("Time_of_Day").count().toPandas()

plt.figure(figsize=(7, 7))
plt.pie(pdf_time["count"], labels=pdf_time["Time_of_Day"], autopct="%1.1f%%")
plt.title("Crime Distribution by Time of Day")
plt.show()

df_avg_age = df.groupBy("Crime_Description").agg({"Victim_Age": "avg"}) \
               .withColumnRenamed("avg(Victim_Age)", "Avg_Victim_Age") \
               .orderBy(col("Avg_Victim_Age").desc())

df_avg_age = df.groupBy("Crime_Description").agg({"Victim_Age": "avg"}) \
               .withColumnRenamed("avg(Victim_Age)", "Avg_Victim_Age") \
               .orderBy(col("Avg_Victim_Age").desc())

pdf_avg_age = df_avg_age.toPandas()

plt.figure(figsize=(12, 5))
sns.barplot(x="Avg_Victim_Age", y="Crime_Description", data=pdf_avg_age.head(10))
plt.title("Top 10 Crimes by Average Victim Age")
plt.xlabel("Average Victim Age")
plt.ylabel("Crime Type")
plt.show()

df_age_group = df.withColumn("Age_Group",
    when(col("Victim_Age") < 18, "Under 18")
    .when((col("Victim_Age") >= 18) & (col("Victim_Age") <= 30), "18-30")
    .when((col("Victim_Age") >= 31) & (col("Victim_Age") <= 50), "31-50")
    .otherwise("Above 50"))

pdf_age = df_age_group.groupBy("Age_Group").count().toPandas()

plt.figure(figsize=(8, 5))
sns.barplot(x="Age_Group", y="count", data=pdf_age)
plt.title("Crime Count by Victim Age Group")
plt.xlabel("Age Group")
plt.ylabel("Crime Count")
plt.show()

print("✅ Crime Analysis Completed Successfully!")